### PR TITLE
Added delete_all_recordings method

### PR DESCRIPTION
**Pull request by zacho112**

### CODE REVIEW

**Comment by yuppity** [comment]
Thank you! I'll merge as soon as I've got some time to ensure this exists on the earlier UniFi Video versions as well.

**Comment by zacho112** [comment]
I forgot to mention, I’ve tested it on 3.10.11.

Should I add an example in the readme as well?

**Comment by yuppity** [comment]
Great, I'll skip 3.10.11. README example isn't necessary but I'll happily merge it if you want to include it.

If it turns out that 3.9.12 doesn't have this then I'd also like a *Warning* section in the docstring ([example](https://github.com/yuppity/unifi-video-api/blob/403cf78868044ea7fad1817cc75b9bb64eedc745/unifi_video/camera.py#L241-L245)). I'll let you know.

**Comment by yuppity** [comment]
Sorry it took this long. Had to find the time to setup 3.9.12 with dummy recordings, without having a camera attached etc.

Thanks again!

**Pull request merged**
