### PR TITLE
handle width parameter same as camera.snapshot

### LINKED ISSUE #32: Maximum size recording snapshot (just like camera)
Currently there is a difference between camera.snapshot() and recording.snapshot(). For camera.snapshot() you can pass 0 for the width (this is also the default) and get the full resolution image from the server. For recording.shapshot() there is also a width parameter (which defaults to 600), but the handling of the width==0 case is different. As I normally want whatever resolution the server can provide, I would like the same behavior in both cases.

I created a pull request ( https://github.com/yuppity/unifi-video-api/pull/29 ) to do just that. It basically copies the same exact code to recording.snapshot that is already used in camera.snapshot

This change may affect people who do not specify a width parameter as this changes the default from 600 to "the maximum the server can provide". I guess an option would be to make the default 600 again, but that kind of keeps the difference between the same methods on the 2 classes (Camera / Recording) which is a bit odd.

Other than that, I am still really enjoying this project!

### PR DESCRIPTION
**Pull request by donaldrs**
camera.snapshot has width=0 => whatever the server returns (max size). This change also implements that behavior for recording.snapshot

### CODE REVIEW

**Comment by yuppity** [comment]
Looks good to me, thank you! 

> This change may affect people who do not specify a width parameter as this changes the default from 600 to "the maximum the server can provide". I guess an option would be to make the default 600 again, but that kind of keeps the difference between the same methods on the 2 classes (Camera / Recording) which is a bit odd.

I had the same concern but ultimately consider the second point more convincing. Leave it as is.

I'll merge this soon.

**Comment by donaldrs** [comment]
Small other suggestion. Could you add “self.uuid = data[‘uuid’]” in load_data() for camera? I now have to access the _data to get the uuid and it would be helpful to just expose that value.

 

Greetings,

Richard

**Comment by donaldrs** [comment]
Hi,

 

I know the answer is probably “no”, but I want to try anyway…. As Unifi Video is end-of-life, do you have any plans to support Unifi Protect on the Cloudkey (Gen2 plus specifically)?

 

There are some other libraries that seem to support that but not as nice as yours and they seem to lack functionality (like downloading video for a given event).

 

Kind regards,

Richard

 

From: yuppity ***@***.***>
Reply to: yuppity/unifi-video-api ***@***.***>
Date: Tuesday, 9 February 2021 at 19:22
To: yuppity/unifi-video-api ***@***.***>
Cc: donaldrs ***@***.***>, Author ***@***.***>
Subject: Re: [yuppity/unifi-video-api] handle width parameter same as camera.snapshot (#29)

 

Looks good to me, thank you!

This change may affect people who do not specify a width parameter as this changes the default from 600 to "the maximum the server can provide". I guess an option would be to make the default 600 again, but that kind of keeps the difference between the same methods on the 2 classes (Camera / Recording) which is a bit odd.

I had the same concern but ultimately consider the second point more convincing. Leave it as is.

I'll merge this soon.

**Comment by yuppity** [comment]
If I become a Protect user then I'll very likely look into writing a similar package for UniFi Protect. At the moment though, I haven't given any thought to switching so even if I do eventually end up doing so, it won't be any time soon.

**Pull request merged**
